# Generated by Django 4.1.8 on 2023-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnkiCard',
            fields=[
                ('anki_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('front_side', models.TextField(default='')),
                ('back_side', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CardsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='studyplatform.ankicard')),
            ],
        ),
    ]
