# Generated by Django 4.1.8 on 2023-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsset',
            name='set_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ankicard',
            name='back_side',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='ankicard',
            name='image',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
