# Generated by Django 4.1.8 on 2023-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0002_cardsset_set_name_alter_ankicard_back_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankicard',
            name='anki_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
