# Generated by Django 4.1.8 on 2023-05-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0003_alter_ankicard_anki_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsset',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='cardsset',
            name='id',
        ),
        migrations.AddField(
            model_name='cardsset',
            name='cards_set_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CardtoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='studyplatform.ankicard')),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplatform.cardsset')),
            ],
        ),
    ]
