# Generated by Django 4.1.8 on 2023-05-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0004_remove_cardsset_cards_remove_cardsset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankicard',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
