# Generated by Django 4.1.8 on 2023-05-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0005_alter_ankicard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoset',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='studyplatform.cardsset'),
        ),
    ]
