# Generated by Django 4.1.8 on 2023-05-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0006_alter_cardtoset_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoset',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to='studyplatform.cardsset'),
        ),
    ]
