# Generated by Django 4.1.8 on 2023-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplatform', '0007_alter_cardtoset_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsset',
            name='cards',
            field=models.ManyToManyField(to='studyplatform.ankicard'),
        ),
        migrations.DeleteModel(
            name='CardtoSet',
        ),
    ]
